# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/

    steps:
      - checkout

      - run:
          name: Test API
          command: |
            pip install virtualenv
            virtualenv -p python3 env
            source venv/bin/activate
            pip install -r holdette-api/requirements.txt
            python3 holdette-api/tests
            deactivate
