# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: ubuntu

    steps:
      - checkout

      - run:
          name: Test API
          command: |
            apt install python3-pip
            pip install virtualenv
            virtualenv -p python3 env
            source venv/bin/activate
            pip install -r holdette-api/requirements.txt
            python3 holdette-api/tests
            deactivate
