# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4

    steps:
      - checkout

      - run:
          name: Test API
          command: |
            sudo pip install --upgrade pip
            sudo pip install virtualenv
            virtualenv -p python3 env
            source env/bin/activate
            pip install -r holdette-api/requirements.txt
            python3 holdette-api/tests
            deactivate
